---
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).
  external_labels:
    cluster: 'tidb-c1-v409'
    monitor: "prometheus"

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'node.rules.yml'
  - 'blacker.rules.yml'
  - 'bypass.rules.yml'
  - 'pd.rules.yml'
  - 'tidb.rules.yml'
  - 'tikv.rules.yml'
  - 'tikv.accelerate.rules.yml'
alerting:
 alertmanagers:
 - static_configs:
   - targets:
     - '192.168.12.31:19093'

scrape_configs:
  - job_name: "overwritten-nodes"
    honor_labels: true # don't overwrite job & instance labels
    static_configs:
    - targets:
      - '192.168.12.31:19100'
      - '192.168.12.32:19100'
      - '192.168.12.33:19100'
      - '192.168.12.31:29100'
      - '192.168.12.32:29100'
      - '192.168.12.33:29100'
    relabel_configs:
      - source_labels: [ '__address__' ]
        regex: '(.*):19100'
        target_label: 'cluster'
        replacement: 'tidb-c1-v409'
      - source_labels: [ '__address__' ]
        regex: '(.*):29100'
        target_label: 'cluster'
        replacement: 'tidb-c2-v409'

    
  - job_name: "tidb"
    honor_labels: true # don't overwrite job & instance labels
    static_configs:
    - targets:
      - '192.168.12.31:12080'
      - '192.168.12.32:12080'
      - '192.168.12.33:12080'
      - '192.168.12.31:22080'
      - '192.168.12.32:22080'
      - '192.168.12.33:22080'
    relabel_configs:
      - source_labels: [ '__address__' ]
        regex: '(.*):12080'
        target_label: 'cluster'
        replacement: 'tidb-c1-v409'
      - source_labels: [ '__address__' ]
        regex: '(.*):22080'
        target_label: 'cluster'
        replacement: 'tidb-c2-v409'


  - job_name: "tikv"
    honor_labels: true # don't overwrite job & instance labels
    static_configs:
    - targets:
      - '192.168.12.31:12180'
      - '192.168.12.32:12180'
      - '192.168.12.33:12180'
      - '192.168.12.31:22180'
      - '192.168.12.32:22180'
      - '192.168.12.33:22180'
    relabel_configs:
      - source_labels: [ '__address__' ]
        regex: '(.*):12180'
        target_label: 'cluster'
        replacement: 'tidb-c1-v409'
      - source_labels: [ '__address__' ]
        regex: '(.*):22180'
        target_label: 'cluster'
        replacement: 'tidb-c2-v409'


  - job_name: "pd"
    honor_labels: true # don't overwrite job & instance labels
    static_configs:
    - targets:
      - '192.168.12.31:12379'
      - '192.168.12.32:12379'
      - '192.168.12.33:12379'
      - '192.168.12.31:22379'
      - '192.168.12.32:22379'
      - '192.168.12.33:22379'
    relabel_configs:
      - source_labels: [ '__address__' ]
        regex: '(.*):12379'
        target_label: 'cluster'
        replacement: 'tidb-c1-v409'
      - source_labels: [ '__address__' ]
        regex: '(.*):22379'
        target_label: 'cluster'
        replacement: 'tidb-c2-v409'

  - job_name: "tidb_port_probe"
    scrape_interval: 30s
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
    - targets:
      - '192.168.12.31:12080'
      - '192.168.12.32:12080'
      - '192.168.12.33:12080'
      - '192.168.12.31:22080'
      - '192.168.12.32:22080'
      - '192.168.12.33:22080'
      labels:
        group: 'tidb'
    - targets:
      - '192.168.12.31:12180'
      - '192.168.12.32:12180'
      - '192.168.12.33:12180'
      - '192.168.12.31:22180'
      - '192.168.12.32:22180'
      - '192.168.12.33:22180'
      labels:
        group: 'tikv'
    - targets:
      - '192.168.12.31:12379'
      - '192.168.12.32:12379'
      - '192.168.12.33:12379'
      - '192.168.12.31:22379'
      - '192.168.12.32:22379'
      - '192.168.12.33:22379'
      labels:
        group: 'pd'
    - targets:
      - '192.168.12.34:3000'
      labels:
        group: 'grafana'
    - targets:
      - '192.168.12.31:19100'
      - '192.168.12.32:19100'
      - '192.168.12.33:19100'
      - '192.168.12.31:29100'
      - '192.168.12.32:29100'
      - '192.168.12.33:29100'
      labels:
        group: 'node_exporter'
    - targets:
      - '192.168.12.31:19115'
      - '192.168.12.32:19115'
      - '192.168.12.33:19115'
      - '192.168.12.31:29115'
      - '192.168.12.32:29115'
      - '192.168.12.33:29115'
      labels:
        group: 'blackbox_exporter'
    relabel_configs:
      - source_labels: [ '__address__' ]
        regex: '((.*):12080)|((.*):12180)|((.*):12379)|((.*):19100)|((.*):19115)'
        target_label: 'cluster'
        replacement: 'tidb-c1-v409'
      - source_labels: [ '__address__' ]
        regex: '((.*):22080)|((.*):22180)|((.*):22379)|((.*):29100)|((.*):29115)'
        target_label: 'cluster'
        replacement: 'tidb-c2-v409'
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.12.34:9115
 
  - job_name: "blackbox_exporter_192.168.12.31:19115_icmp"
    scrape_interval: 6s
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
    - targets:
      - '192.168.12.31'
      - '192.168.12.32'
      - '192.168.12.33'
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)(:80)?
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__param_target]
        regex: (.*)
        target_label: ping
        replacement: ${1}
      - source_labels: []
        regex: .*
        target_label: __address__
        replacement: 192.168.12.31:19115

  - job_name: "blackbox_exporter_192.168.12.32:19115_icmp"
    scrape_interval: 6s
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
    - targets:
      - '192.168.12.31'
      - '192.168.12.32'
      - '192.168.12.33'
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)(:80)?
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__param_target]
        regex: (.*)
        target_label: ping
        replacement: ${1}
      - source_labels: []
        regex: .*
        target_label: __address__
        replacement: 192.168.12.32:19115

  - job_name: "blackbox_exporter_192.168.12.33:19115_icmp"
    scrape_interval: 6s
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
    - targets:
      - '192.168.12.31'
      - '192.168.12.32'
      - '192.168.12.33'
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)(:80)?
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__param_target]
        regex: (.*)
        target_label: ping
        replacement: ${1}
      - source_labels: []
        regex: .*
        target_label: __address__
        replacement: 192.168.12.33:19115

  - job_name: "blackbox_exporter_192.168.12.31:29115_icmp"
    scrape_interval: 6s
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
    - targets:
      - '192.168.12.31'
      - '192.168.12.32'
      - '192.168.12.33'
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)(:80)?
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__param_target]
        regex: (.*)
        target_label: ping
        replacement: ${1}
      - source_labels: []
        regex: .*
        target_label: __address__
        replacement: 192.168.12.31:29115

  - job_name: "blackbox_exporter_192.168.12.32:29115_icmp"
    scrape_interval: 6s
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
    - targets:
      - '192.168.12.31'
      - '192.168.12.32'
      - '192.168.12.33'
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)(:80)?
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__param_target]
        regex: (.*)
        target_label: ping
        replacement: ${1}
      - source_labels: []
        regex: .*
        target_label: __address__
        replacement: 192.168.12.32:29115

  - job_name: "blackbox_exporter_192.168.12.33:29115_icmp"
    scrape_interval: 6s
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
    - targets:
      - '192.168.12.31'
      - '192.168.12.32'
      - '192.168.12.33'
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)(:80)?
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__param_target]
        regex: (.*)
        target_label: ping
        replacement: ${1}
      - source_labels: []
        regex: .*
        target_label: __address__
        replacement: 192.168.12.33:29115
